### ISSUE TITLE
Issue with grunt

### ISSUE THREAD

**Issue by joseeight** [benignware/grunt-css-wrap#3]
Hi guys,

`npm install grunt-css-wrap` is broken, it looks like the recent change broke it:
```
npm ERR! notarget No compatible version found: css-wrap@'>=0.0.1 <0.1.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by rexblack** [comment]
Thank you very much for your report. Yes, you're right. I separated css-wrap logic from the grunt-plugin and apparently didn't tested the grunt-plugin. the right version should be 0.1.0. You should be able to fix this yourself to get it working for your recent needs temporarily. i will publish a fixed version asap.

**Comment by oller** [comment]
Hi, looks like a great script, looking forward to trying it out.  

I've just encountered this error too with the `npm install`, to clarify how should we patch this in the meantime, seeing as the error is with the install initially, there's no files to edit.

**Comment by rexblack** [comment]
It'll be a quick task to fix this and publish a new version. I'm going to do it in lunch break and give you notice then.

**Comment by oller** [comment]
:+1:

**Comment by rexblack** [comment]
Didn't had any lunch break yesterday ;-)
It should be fixed now.

**Comment by oller** [comment]
~~haha cheers!  Does this need a release tag to push it though to npm?~~
I guess not, thanks again!

**Comment by rexblack** [comment]
This is indeed not needed for NPM. In order to keep release tags consistent to published versions it must be manually added. Thanks for your reminder! ;-)

**Comment by joseeight** [comment]
Thanks :)
